[Database]
Host = "localhost"
Port = "3306"
Name = "exp"
Username = "exp"
Password = "exp"
 
[Web]
Domain = "example.com"
Port = "443"
IsBehindReverseProxy = true
WriteTimeout = 30
ReadTimeout = 30
DocumentRoot = "/home/websrv/"
SessionName = "PHPSID"
StaticDir = "static"
SessionMaxAge = 86400
SessionSecure = true
SessionHTTPOnly = true
SessionSecret = "RandomString"
LogFile = "gin.log"
AllowIPAddr = ["1.2.3.4"]

